services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: your-telegram-token-here
      - key: OPENROUTER_API_KEY
        value: your-openrouter-api-key-here
